### ISSUE TITLE
PHP Notice:  Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name

### ISSUE THREAD

**Issue by GaryJones** [edsonmedina/php_testability#81]
Follow on from #80.

![screenshot 2017-07-14 10 09 59](https://user-images.githubusercontent.com/88371/28206133-bb58579e-687c-11e7-88db-128fb607ee24.png)

```
PHP Notice:  Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 79

Notice: Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 79
PHP Notice:  Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 85

Notice: Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 85
```

Using `-vvv`, it suggests that the troublesome file is [`genesis-admin-boxes-holder.php`](https://gist.github.com/GaryJones/682dc39dc27ec9ea11e3bb9e25c558d4).

**Comment by edsonmedina** [comment]
Fixed

**Comment by GaryJones** [comment]
Updated to latest `master`, but still not fixed:

![screenshot 2017-07-14 12 09 17](https://user-images.githubusercontent.com/88371/28210011-4e24c6e2-688d-11e7-8813-69d08fafb448.png)

```
PHP Notice:  Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 102

Notice: Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 102
PHP Notice:  Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 106

Notice: Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 106
```

**Comment by edsonmedina** [comment]
Thanks for your patience.

**Comment by GaryJones** [comment]
@edsonmedina All fixed, thank you for your persistence :-)

![screenshot 2017-07-14 12 27 48](https://user-images.githubusercontent.com/88371/28210559-e398674a-688f-11e7-95e6-db9696bf4078.png)
